### ISSUE TITLE
Add 0049 Group Anagrams solution.

### ISSUE THREAD

**Issue by arushitrivedi** [kriti-002/LeetCode-Solutions#6]
Hi @kriti-002! I'd like to contribute to your project by adding the solution to this Leetcode medium problem. Please assign me to work on this issue under the tag of "hacktoberfest"

**Comment by RAGHAVS1304** [comment]
Hlo @kriti-002 I keep solving problems on daily basis.I want to contribute in solving these problems.Please assign this to me under the hacktoberfest label.
Thanks

**Comment by dhruvsingal24** [comment]
Hi @kriti-002 I have solved this problem and would like to contribute to it.Please assign this issue to me under the hactoberfest label.
